import React, { useState } from 'react';
import { 
  User, 
  GraduationCap, 
  ShieldCheck, 
  BookOpen, 
  Calendar, 
  Mail, 
  Phone, 
  Heart, 
  Home, 
  Lock,
  Key,
  Eye,
  EyeOff,
  Copy,
  Check,
  Award,
  Printer
} from 'lucide-react';
import GisEmblem from '../../../components/ui/GisEmblem';

export default function StudentProfile({ student = {}, summary = {}, onViewReportCard }) {
  const [showPassword, setShowPassword] = useState(false);
  const [copiedField, setCopiedField] = useState(null);

  const studentData = {
    name: student.name || 'Aarav Kumar',
    firstName: (student.name || 'Aarav Kumar').split(' ')[0] || 'Aarav',
    lastName: (student.name || 'Aarav Kumar').split(' ').slice(1).join(' ') || 'Kumar',
    class: student.class || '10-A',
    rollNo: student.rollNo || '10A-01',
    admissionNo: 'GIS-2024-884',
    academicYear: '2026-27',
    academicYearNum: '2026',
    email: student.email || 'student.aarav@greenfieldis.edu',
    guardian: 'Mr. Rajesh Kumar',
    guardianPhone: '+91 98765 11001',
    house: 'Emerald Royals House',
    dob: '14-Aug-2010',
    bloodGroup: 'B+',
    address: '402, Royal Palms, Koramangala, Bangalore – 560034',
    subjects: student.subjects || ['Mathematics', 'Science (Chemistry & STEM)', 'Physics & Mechanics', 'English Language & Literature', 'Social Science', 'Computer Science & AI'],
  };

  // Student Password Formula: [FirstName] + [first 4 letters of LastName] + {AcademicYear}
  const last4 = (studentData.lastName.replace(/[^a-zA-Z]/g, '') + 'xxxx').slice(0, 4);
  const autoGeneratedPassword = `${studentData.firstName}${last4}${studentData.academicYearNum}`;

  const copyToClipboard = (text, fieldName) => {
    navigator.clipboard?.writeText(text);
    setCopiedField(fieldName);
    setTimeout(() => setCopiedField(null), 2000);
  };

  return (
    <div className="space-y-6">
      
      {/* ── TOP HERO PROFILE CARD ── */}
      <div className="bg-white rounded-2xl p-6 sm:p-8 border border-gray-200 shadow-2xs relative overflow-hidden">
        
        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-6 relative z-10">
          
          {/* Avatar with Status Ring */}
          <div className="relative">
            <div className="w-22 h-22 sm:w-24 sm:h-24 rounded-2xl bg-gradient-to-tr from-[#0B2E23] to-[#1a5e4c] p-1 shadow-md flex items-center justify-center">
              <div className="w-full h-full bg-[#FAF8F3] rounded-xl flex items-center justify-center text-forest-900 font-serif font-bold text-3xl border border-[#C5A880]/40">
                {studentData.name.split(' ').map((n) => n[0]).join('')}
              </div>
            </div>
            <div 
              className="absolute -bottom-1 -right-1 bg-emerald-600 text-white p-1.5 rounded-lg border-2 border-white shadow-xs" 
              title="Enrolled Regular Student"
            >
              <ShieldCheck className="w-4 h-4" />
            </div>
          </div>

          {/* Student Info */}
          <div className="flex-1 space-y-1.5">
            <div className="flex items-center gap-2.5 flex-wrap">
              <h2 className="font-serif text-2xl sm:text-3xl font-bold text-forest-900 tracking-tight">
                {studentData.name}
              </h2>
              <span className="px-3 py-0.5 rounded-full text-xs font-mono font-bold bg-forest-50 text-forest-900 border border-forest-800/20">
                Class {studentData.class}
              </span>
              <span className="px-3 py-0.5 rounded-full text-xs font-bold bg-emerald-50 text-emerald-800 border border-emerald-300">
                Roll: {studentData.rollNo}
              </span>
            </div>

            <p className="text-sm font-bold text-[#8C6218]">{studentData.house} &bull; Admission No: {studentData.admissionNo}</p>
            <p className="text-xs text-gray-500">Greenfield International School &bull; Academic Session {studentData.academicYear}</p>
          </div>

          {/* Report Card Button */}
          <div className="shrink-0 flex sm:flex-col gap-2">
            <button
              type="button"
              onClick={onViewReportCard}
              className="px-4 py-2.5 rounded-xl bg-forest-900 hover:bg-forest-800 text-gold-300 font-bold text-xs flex items-center justify-center gap-2 shadow-sm transition-all cursor-pointer"
            >
              <Award className="w-4 h-4 text-gold-400" />
              <span>Official Report Card</span>
            </button>
          </div>

        </div>

      </div>

      {/* ── 2-COLUMN DETAILS GRID ── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* ── CARD 1: ACADEMIC CURRICULUM & GUARDIAN ── */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-2xs space-y-5">
          <div className="flex items-center gap-3 pb-3 border-b border-gray-100">
            <div className="p-2 rounded-xl bg-forest-50 text-forest-900 border border-forest-800/15">
              <GraduationCap className="w-5 h-5 text-gold-600" />
            </div>
            <div>
              <h3 className="font-serif text-base font-bold text-forest-900">
                Enrolled Academic Disciplines & Bio
              </h3>
              <p className="text-xs text-gray-500">Class 10-A Core Curriculum & Guardian Info</p>
            </div>
          </div>

          <div className="space-y-4 text-xs">
            <div>
              <p className="text-[10.5px] font-bold text-gray-400 uppercase tracking-wider mb-2">
                Class 10-A Core Subjects
              </p>
              <div className="flex flex-wrap gap-2">
                {studentData.subjects.map((sub) => (
                  <span 
                    key={sub} 
                    className="px-3 py-1.5 rounded-xl bg-[#FAF8F3] border border-[#C5A880]/30 font-bold text-forest-900 flex items-center gap-1.5"
                  >
                    <BookOpen className="w-3.5 h-3.5 text-gold-600" />
                    <span>{sub}</span>
                  </span>
                ))}
              </div>
            </div>

            <div className="pt-2 border-t border-gray-100 space-y-2.5 text-xs text-gray-600">
              <div className="flex items-center justify-between">
                <span>Guardian / Parent Name:</span>
                <strong className="text-forest-900">{studentData.guardian}</strong>
              </div>
              <div className="flex items-center justify-between">
                <span>Registered Parent Phone:</span>
                <strong className="text-forest-900 font-mono">{studentData.guardianPhone}</strong>
              </div>
              <div className="flex items-center justify-between">
                <span>Date of Birth & Blood Group:</span>
                <strong className="text-forest-900">{studentData.dob} &bull; Blood Group: {studentData.bloodGroup}</strong>
              </div>
              <div className="flex items-center justify-between">
                <span>Residential Address:</span>
                <strong className="text-forest-900 truncate max-w-xs">{studentData.address}</strong>
              </div>
            </div>
          </div>
        </div>

        {/* ── CARD 2: ACCOUNT CREDENTIALS & SECURITY ── */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-2xs space-y-5">
          <div className="flex items-center justify-between pb-3 border-b border-gray-100">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-amber-50 text-amber-900 border border-amber-200">
                <Lock className="w-5 h-5 text-amber-700" />
              </div>
              <div>
                <h3 className="font-serif text-base font-bold text-forest-900">
                  Student Credentials & Access Security
                </h3>
                <p className="text-xs text-gray-500">Auto-generated institutional student credentials</p>
              </div>
            </div>

            <span className="px-2.5 py-1 rounded-full text-[10.5px] font-bold bg-emerald-50 text-emerald-800 border border-emerald-300">
              Active Session
            </span>
          </div>

          <div className="space-y-3.5 text-xs">
            
            {/* Institutional Email */}
            <div className="p-3.5 rounded-xl bg-[#FAF8F3] border border-[#C5A880]/30 flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <Mail className="w-4 h-4 text-gold-600 shrink-0" />
                <div>
                  <p className="text-[10px] text-gray-400 uppercase font-bold">Student Portal ID</p>
                  <p className="font-mono text-xs font-bold text-forest-900">{studentData.email}</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => copyToClipboard(studentData.email, 'email')}
                className="p-1.5 rounded-lg hover:bg-gray-200 text-gray-500 transition-colors cursor-pointer"
                title="Copy student email"
              >
                {copiedField === 'email' ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>

            {/* Auto Password with Formula Explanation */}
            <div className="p-3.5 rounded-xl bg-amber-50/60 border border-amber-200/80 space-y-2">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Key className="w-4 h-4 text-amber-700" />
                  <span className="text-[10px] uppercase font-bold text-amber-900 tracking-wider">
                    Auto-Generated Student Password
                  </span>
                </div>
                
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="flex items-center gap-1 text-[11px] font-bold text-amber-900 hover:text-forest-900 bg-white px-2 py-0.5 rounded-md border border-amber-300 shadow-2xs cursor-pointer"
                >
                  {showPassword ? (
                    <>
                      <EyeOff className="w-3 h-3 text-amber-700" />
                      <span>Hide</span>
                    </>
                  ) : (
                    <>
                      <Eye className="w-3 h-3 text-amber-700" />
                      <span>View Password</span>
                    </>
                  )}
                </button>
              </div>

              {/* Password Display Box */}
              <div className="flex items-center justify-between bg-white p-2.5 rounded-lg border border-amber-200">
                <span className="font-mono font-bold text-xs tracking-wider text-forest-900">
                  {showPassword ? autoGeneratedPassword : '••••••••••••••••'}
                </span>
                
                <button
                  type="button"
                  onClick={() => copyToClipboard(autoGeneratedPassword, 'password')}
                  className="p-1 text-gray-400 hover:text-forest-900 cursor-pointer"
                  title="Copy password"
                >
                  {copiedField === 'password' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>

              {/* Formula */}
              <div className="text-[10.5px] text-amber-900/90 leading-tight pt-1">
                <strong>Formula:</strong> <code className="bg-amber-100/80 px-1 py-0.5 rounded text-amber-950 font-mono">[FirstName] + [first 4 letters of LastName] + [AcademicYear]</code>
                <p className="mt-0.5 text-gray-600">
                  Example: <code>{studentData.firstName}</code> + <code>{last4}</code> + <code>{studentData.academicYearNum}</code> &rarr; <strong className="font-mono text-forest-900">{autoGeneratedPassword}</strong>
                </p>
              </div>
            </div>

          </div>
        </div>

      </div>

    </div>
  );
}
