import React, { useState } from 'react';
import { 
  User, 
  Mail, 
  Phone, 
  Briefcase, 
  Clock, 
  BookOpen, 
  GraduationCap, 
  Building2, 
  ShieldCheck, 
  Sparkles, 
  Calendar,
  CheckCircle2,
  Award,
  Key,
  Eye,
  EyeOff,
  Copy,
  Check,
  Lock,
  Smartphone
} from 'lucide-react';
import GisEmblem from '../../../components/ui/GisEmblem';

export default function TeacherProfile({ profile: teacherInfo = {} }) {
  const [showPassword, setShowPassword] = useState(false);
  const [copiedField, setCopiedField] = useState(null);

  const teacher = {
    name: teacherInfo.name || 'Ananya Sharma',
    firstName: (teacherInfo.name || 'Ananya Sharma').split(' ')[0] || 'Ananya',
    lastName: (teacherInfo.name || 'Ananya Sharma').split(' ').slice(1).join(' ') || 'Sharma',
    role: teacherInfo.role || 'Mathematics Faculty',
    employeeId: teacherInfo.employeeId || 'GIS-T-023',
    department: teacherInfo.department || 'Senior Secondary Mathematics',
    email: teacherInfo.email || 'ananya.sharma@greenfieldis.edu',
    phone: teacherInfo.phone || '+91 98450 12345',
    joiningYear: '2024',
    workingHours: teacherInfo.workingHours || '8:00 AM – 4:00 PM',
    assignedClasses: teacherInfo.assignedClasses || ['8-A', '9-B', '10-A'],
    subjects: teacherInfo.subjects || ['Mathematics', 'Advanced Calculus', 'Trigonometry'],
    experience: '8 Years (Greenfield International School)',
    qualifications: 'M.Sc. Mathematics (Gold Medalist), B.Ed',
    officeRoom: 'Senior Secondary Faculty Wing B, Desk 14'
  };

  // Formula: [FirstName] + [first 4 letters of LastName] + [gisyear of joining]
  const last4 = (teacher.lastName.replace(/[^a-zA-Z]/g, '') + 'xxxx').slice(0, 4);
  const autoGeneratedPassword = `${teacher.firstName}${last4}gis${teacher.joiningYear}`;

  const copyToClipboard = (text, fieldName) => {
    navigator.clipboard?.writeText(text);
    setCopiedField(fieldName);
    setTimeout(() => setCopiedField(null), 2000);
  };

  return (
    <div className="space-y-6">
      
      {/* ── TOP HERO PROFILE CARD ── */}
      <div className="bg-white rounded-2xl p-6 sm:p-8 border border-gray-200 shadow-2xs relative overflow-hidden">
        
        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-6 relative z-10">
          
          {/* Avatar with Status Ring */}
          <div className="relative">
            <div className="w-22 h-22 sm:w-24 sm:h-24 rounded-2xl bg-gradient-to-tr from-[#0B2E23] to-[#1a5e4c] p-1 shadow-md flex items-center justify-center">
              <div className="w-full h-full bg-[#FAF8F3] rounded-xl flex items-center justify-center text-forest-900 font-serif font-bold text-3xl border border-[#C5A880]/40">
                {teacher.name.split(' ').map((n) => n[0]).join('')}
              </div>
            </div>
            <div 
              className="absolute -bottom-1 -right-1 bg-emerald-600 text-white p-1.5 rounded-lg border-2 border-white shadow-xs" 
              title="Verified Permanent Faculty"
            >
              <ShieldCheck className="w-4 h-4" />
            </div>
          </div>

          {/* Teacher Identity */}
          <div className="flex-1 space-y-1.5">
            <div className="flex items-center gap-2.5 flex-wrap">
              <h2 className="font-serif text-2xl sm:text-3xl font-bold text-forest-900 tracking-tight">
                {teacher.name}
              </h2>
              <span className="px-3 py-0.5 rounded-full text-xs font-mono font-bold bg-forest-50 text-forest-900 border border-forest-800/20">
                {teacher.employeeId}
              </span>
              <span className="px-3 py-0.5 rounded-full text-xs font-bold bg-emerald-50 text-emerald-800 border border-emerald-300">
                Permanent Senior Faculty
              </span>
            </div>

            <p className="text-sm font-bold text-[#8C6218]">{teacher.role}</p>
            <p className="text-xs text-gray-500">{teacher.department} &bull; {teacher.officeRoom}</p>
          </div>

          {/* Quick Stats Chips */}
          <div className="flex sm:flex-col gap-2 shrink-0">
            <div className="px-4 py-2 rounded-xl bg-[#FAF8F3] border border-[#C5A880]/30 text-center">
              <p className="text-[10px] text-gray-500 uppercase tracking-wider font-bold">Assigned Sections</p>
              <p className="font-serif text-lg font-bold text-forest-900">{teacher.assignedClasses.length} Classes</p>
            </div>
            <div className="px-4 py-2 rounded-xl bg-emerald-50 border border-emerald-200 text-center">
              <p className="text-[10px] text-emerald-800 uppercase tracking-wider font-bold">Attendance Rate</p>
              <p className="font-serif text-lg font-bold text-emerald-900">96.4%</p>
            </div>
          </div>

        </div>

      </div>

      {/* ── 2-COLUMN DETAILS GRID ── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* ── CARD 1: TEACHING RESPONSIBILITIES & CURRICULUM ── */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-2xs space-y-5">
          <div className="flex items-center gap-3 pb-3 border-b border-gray-100">
            <div className="p-2 rounded-xl bg-forest-50 text-forest-900 border border-forest-800/15">
              <BookOpen className="w-5 h-5 text-gold-600" />
            </div>
            <div>
              <h3 className="font-serif text-base font-bold text-forest-900">
                Academic & Teaching Responsibilities
              </h3>
              <p className="text-xs text-gray-500">Curricular syllabus, class sections, and weekly hours</p>
            </div>
          </div>

          <div className="space-y-4">
            
            {/* Assigned Classes */}
            <div>
              <p className="text-[11px] font-bold text-gray-400 uppercase tracking-wider mb-2">
                Assigned Class Sections
              </p>
              <div className="flex flex-wrap gap-2">
                {teacher.assignedClasses.map((cls) => (
                  <span 
                    key={cls} 
                    className="px-3 py-1.5 rounded-xl bg-[#FAF8F3] border border-[#C5A880]/40 text-xs font-bold text-forest-900 flex items-center gap-1.5"
                  >
                    <GraduationCap className="w-3.5 h-3.5 text-gold-600" />
                    <span>Class {cls}</span>
                  </span>
                ))}
              </div>
            </div>

            {/* Primary Subjects */}
            <div>
              <p className="text-[11px] font-bold text-gray-400 uppercase tracking-wider mb-2">
                Primary Subject Disciplines
              </p>
              <div className="flex flex-wrap gap-2">
                {teacher.subjects.map((sub) => (
                  <span 
                    key={sub} 
                    className="px-3 py-1 rounded-lg bg-forest-50 border border-forest-800/20 text-xs font-bold text-forest-900"
                  >
                    {sub}
                  </span>
                ))}
              </div>
            </div>

            {/* Metadata Rows */}
            <div className="pt-2 border-t border-gray-100 space-y-2.5 text-xs">
              <div className="flex items-center justify-between text-gray-600">
                <span>Working Hours:</span>
                <strong className="text-forest-900 font-mono">{teacher.workingHours}</strong>
              </div>
              <div className="flex items-center justify-between text-gray-600">
                <span>Teaching Experience:</span>
                <strong className="text-forest-900">{teacher.experience}</strong>
              </div>
              <div className="flex items-center justify-between text-gray-600">
                <span>Degrees & Honors:</span>
                <strong className="text-forest-900">{teacher.qualifications}</strong>
              </div>
              <div className="flex items-center justify-between text-gray-600">
                <span>Faculty Room:</span>
                <strong className="text-forest-900">{teacher.officeRoom}</strong>
              </div>
            </div>

          </div>
        </div>

        {/* ── CARD 2: ACCOUNT CREDENTIALS & SECURITY ── */}
        <div className="bg-white rounded-2xl border border-gray-200 p-6 shadow-2xs space-y-5">
          <div className="flex items-center justify-between pb-3 border-b border-gray-100">
            <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-amber-50 text-amber-900 border border-amber-200">
                <Lock className="w-5 h-5 text-amber-700" />
              </div>
              <div>
                <h3 className="font-serif text-base font-bold text-forest-900">
                  Account Credentials & Security
                </h3>
                <p className="text-xs text-gray-500">Auto-generated institutional access credentials</p>
              </div>
            </div>

            <span className="px-2.5 py-1 rounded-full text-[10.5px] font-bold bg-emerald-50 text-emerald-800 border border-emerald-300 flex items-center gap-1">
              <CheckCircle2 className="w-3 h-3 text-emerald-600" />
              <span>Active 2FA</span>
            </span>
          </div>

          <div className="space-y-3.5 text-xs">
            
            {/* Institutional Email */}
            <div className="p-3.5 rounded-xl bg-[#FAF8F3] border border-[#C5A880]/30 flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <Mail className="w-4 h-4 text-gold-600 shrink-0" />
                <div>
                  <p className="text-[10px] text-gray-400 uppercase font-bold">Institutional Email</p>
                  <p className="font-mono text-xs font-bold text-forest-900">{teacher.email}</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => copyToClipboard(teacher.email, 'email')}
                className="p-1.5 rounded-lg hover:bg-gray-200 text-gray-500 transition-colors cursor-pointer"
                title="Copy email"
              >
                {copiedField === 'email' ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>

            {/* Official Username */}
            <div className="p-3.5 rounded-xl bg-[#FAF8F3] border border-[#C5A880]/30 flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <User className="w-4 h-4 text-gold-600 shrink-0" />
                <div>
                  <p className="text-[10px] text-gray-400 uppercase font-bold">Faculty Portal Username</p>
                  <p className="font-mono text-xs font-bold text-forest-900">{teacher.employeeId}</p>
                </div>
              </div>
              <button
                type="button"
                onClick={() => copyToClipboard(teacher.employeeId, 'username')}
                className="p-1.5 rounded-lg hover:bg-gray-200 text-gray-500 transition-colors cursor-pointer"
                title="Copy username"
              >
                {copiedField === 'username' ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>

            {/* Auto-Generated Password with Formula Breakdown */}
            <div className="p-3.5 rounded-xl bg-amber-50/60 border border-amber-200/80 space-y-2">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Key className="w-4 h-4 text-amber-700" />
                  <span className="text-[10px] uppercase font-bold text-amber-900 tracking-wider">
                    Institutional Auto-Generated Password
                  </span>
                </div>
                
                {/* Eye toggle button */}
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="flex items-center gap-1 text-[11px] font-bold text-amber-900 hover:text-forest-900 bg-white px-2 py-0.5 rounded-md border border-amber-300 shadow-2xs cursor-pointer"
                >
                  {showPassword ? (
                    <>
                      <EyeOff className="w-3 h-3 text-amber-700" />
                      <span>Hide</span>
                    </>
                  ) : (
                    <>
                      <Eye className="w-3 h-3 text-amber-700" />
                      <span>View Password</span>
                    </>
                  )}
                </button>
              </div>

              {/* Password Display Box */}
              <div className="flex items-center justify-between bg-white p-2.5 rounded-lg border border-amber-200">
                <span className="font-mono font-bold text-xs tracking-wider text-forest-900">
                  {showPassword ? autoGeneratedPassword : '••••••••••••••••'}
                </span>
                
                <button
                  type="button"
                  onClick={() => copyToClipboard(autoGeneratedPassword, 'password')}
                  className="p-1 text-gray-400 hover:text-forest-900 cursor-pointer"
                  title="Copy password"
                >
                  {copiedField === 'password' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
              </div>

              {/* Formula explanation chip */}
              <div className="text-[10.5px] text-amber-900/90 leading-tight pt-1">
                <strong>Formula:</strong> <code className="bg-amber-100/80 px-1 py-0.5 rounded text-amber-950 font-mono">[FirstName] + [first 4 letters of LastName] + gis + [JoiningYear]</code>
                <p className="mt-0.5 text-gray-600">
                  Example: <code>{teacher.firstName}</code> + <code>{last4}</code> + <code>gis</code> + <code>{teacher.joiningYear}</code> &rarr; <strong className="font-mono text-forest-900">{autoGeneratedPassword}</strong>
                </p>
              </div>
            </div>

            {/* Direct Phone */}
            <div className="p-3.5 rounded-xl bg-[#FAF8F3] border border-[#C5A880]/30 flex items-center justify-between">
              <div className="flex items-center gap-2.5">
                <Smartphone className="w-4 h-4 text-gold-600 shrink-0" />
                <div>
                  <p className="text-[10px] text-gray-400 uppercase font-bold">Registered Emergency Phone</p>
                  <p className="font-mono text-xs font-bold text-forest-900">{teacher.phone}</p>
                </div>
              </div>
              <span className="text-[10.5px] font-bold text-emerald-800 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-200">
                SMS Verified
              </span>
            </div>

          </div>
        </div>

      </div>

    </div>
  );
}
